---
title: Trabalho 1 - Uma modelagem matrimonial
author1: Caio Gomes Alves
author2: Daniel Krügel
advisor: Cesar Augusto Taconeli
year: 2023
resumo: |
  `r if(knitr:::is_latex_output()) paste(readLines("resumo.Rmd"),
  collapse = '\n  ')`
palavras-chave: [Regressão linear generalizada, Penalização Lasso, multicolinearidade]
output: tcctemplate::tcc_template
---


```{r setup, include=FALSE}
library(xtable)
## Opções comuns utilizadas em todas as tabelas usando xtable
options(xtable.caption.placement = "top",
        xtable.include.rownames = FALSE,
        xtable.comment = FALSE)
## Opções comuns para o knitr
knitr::opts_chunk$set(echo = FALSE,
                      out.width = "80%",
                      fig.align = "center")
library(tidyverse)
library(hrbrthemes)
library(GGally)
library(glmnet)
library(highcharter)
setwd("~/Faculdade/Regressao linear generalizada/Trabalho 1 - Dados binários")
dados <- read.csv2("divorce.csv")
correlacao <- read.csv2("divorce.csv")
```

# Introdução
\bigskip


```{r, child="introducao.Rmd"}
```

# Material e Métodos
\bigskip

```{r, child="metodologia.Rmd"}
```

# Resultados e Discussão
\bigskip

```{r, child="resultados.Rmd"}
```

# Considerações Finais
\bigskip

```{r, child="consideracoes.Rmd"}
```

```{r, echo=FALSE}
## Se houverem apêndices ou anexos, coloque aqui como TRUE e veja os
## chinks a seguir
apendice <- FALSE
anexo <- FALSE
```


